cluster:
  name: kubernetes
externalServices:
  prometheus:
    host: https://prometheus-prod-32-prod-ca-east-0.grafana.net
    basicAuth:
      username: "${PROMETHEUS_USER}"
      password: ${GRAFANA_SECRET}
  loki:
    host: https://logs-prod-018.grafana.net
    basicAuth:
      username: "${GRAFANA_USER}"
      password: ${GRAFANA_SECRET}
  tempo:
    host: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
    basicAuth:
      username: "${TEMPO_USER}"
      password: ${GRAFANA_SECRET}
metrics:
  enabled: true
  alloy:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: true
  kepler:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: false
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: false
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: kubernetes
    prometheus:
      external:
        url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
kepler:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}