cluster:
  name: kubernetes
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
    auth:
      type: basic
      username: "${PROMETHEUS_USER}"
      password: ${GRAFANA_SECRET}
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-018.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "${GRAFANA_USER}"
      password: ${GRAFANA_SECRET}
clusterMetrics:
  enabled: true
podLogs:
  enabled: true
  extraLogProcessingStages: |-
    stage.drop {
      older_than          = "1h"
      drop_counter_reason = "too old"
    }
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-logs
alloy-metrics:
  enabled: true
alloy-logs:
  enabled: true
