cluster:
  name: kubernetes
destinations:
  - name: akatsuki-prom
    type: prometheus
    url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
    auth:
      type: basic
      username: "${PROMETHEUS_USER}"
      password: ${GRAFANA_SECRET}
  - name: akatsuki-logs
    type: loki
    url: https://logs-prod-018.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "${GRAFANA_USER}"
      password: ${GRAFANA_SECRET}
  - name: akatsuki-traces
    type: otlp
    url: https://tempo-prod-13-prod-ca-east-0.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      username: "${TEMPO_USER}"
      password: ${GRAFANA_SECRET}
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
  - name: akatsuki-profiles
    type: pyroscope
    url: https://profiles-prod-006.grafana.net:443
    auth:
      type: basic
      username: "${PYRO_USER}"
      password: ${GRAFANA_SECRET}
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: akatsuki-prom
    opencost:
      exporter:
        defaultClusterId: kubernetes
      prometheus:
        existingSecretName: akatsuki-prom-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom
  kepler:
    enabled: true
annotationAutodiscovery:
  enabled: true
clusterEvents:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  processors:
    grafanaCloudMetrics:
      enabled: true
autoInstrumentation:
  enabled: true
profiling:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-receiver
            - alloy-profiles
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
alloy-profiles:
  enabled: true
