apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: github-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: runner
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: RUNNER_SCOPE
              value: "org"
            - name: ORG_NAME
              value: {{ .Values.org | quote }}
            - name: LABELS
              value: {{ .Values.labels | quote }}
            - name: RUNNER_WORKDIR
              value: "/tmp/runner"
            - name: EPHEMERAL
              value: "true"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      terminationGracePeriodSeconds: 60
