apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-staging
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["networking","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-staging-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-staging
subjects:
- kind: ServiceAccount
  name: external-dns-staging
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns-staging
    spec:
      serviceAccountName: external-dns-staging
      containers:
      - name: external-dns-staging
        image: k8s.gcr.io/external-dns/external-dns:v0.13.4
        args:
        - --source=service # ingress is also possible
        - --domain-filter=akatsuki.gg # (optional) limit to only akatsuki.gg domains; change to match the zone created above.
        - --zone-id-filter=$CF_ZONE_ID # (optional) limit to a specific zone.
        - --provider=cloudflare
        - --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
        - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request
        env:
        - name: CF_API_KEY
          value: "$CF_API_KEY"
        - name: CF_API_EMAIL
          value: "$CF_API_EMAIL"
