apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-service-staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "next.akatsuki.gg"
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: users-service-staging
              port:
                number: 80
