on:
  workflow_dispatch:

jobs:
  tf-plan-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest commit
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

    - name: Run tf plan
      run: |
        cd staging/tf/
        terraform init
        terraform plan -out tplan -var 'do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
